# Hugo Configuration
# Documentation: https://hugoblox.com/docs/

# The URL the site will be built for
baseURL = "https://hisazumilabweb.netlify.app/"
title = "Hisazumi Lab"

# Theme
# We will use the Hugo Blox modules
module.imports = [
  { path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5" },
  { path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify" },
  { path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-reveal" }
]

defaultContentLanguage = "ja"
hasCJKLanguage = true

[languages.ja]
  languageName = "Japanese"
  contentDir = "content/ja"
  weight = 1

  [languages.ja.menu]
    [[languages.ja.menu.main]]
      name = "ホーム"
      url = "#about"
      weight = 10
    [[languages.ja.menu.main]]
      name = "ニュース"
      url = "#posts"
      weight = 20
    [[languages.ja.menu.main]]
      name = "業績"
      url = "achievements/"
      weight = 30
    [[languages.ja.menu.main]]
      name = "プロジェクト"
      url = "projects-list/"
      weight = 40
    [[languages.ja.menu.main]]
      name = "講義"
      url = "teaching/"
      weight = 50
    [[languages.ja.menu.main]]
      name = "論文"
      url = "publication/"
      weight = 60

[languages.en]
  languageName = "English"
  contentDir = "content/en"
  weight = 2

[params]
  # Site description
  description = "Hisazumi Laboratory"

[security.funcs]
  getenv = ['^HUGO_', '^CI$', 'WC_POST_CSS']

[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"
