# Hugo Configuration
# Documentation: https://hugoblox.com/docs/

# The URL the site will be built for
baseURL = "https://hisazumi.jp/"
title = "Hisazumi Lab"

# Theme
# We will use the Hugo Blox modules
module.imports = [
  { path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5" },
  { path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-core" },
  { path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify" },
  { path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-reveal" }
]

defaultContentLanguage = "ja"
hasCJKLanguage = true

[languages.ja]
  languageName = "Japanese"
  contentDir = "content/ja"
  weight = 1

  [languages.ja.menu]
    [[languages.ja.menu.main]]
      name = "ホーム"
      url = "#about"
      weight = 10
    [[languages.ja.menu.main]]
      name = "ニュース"
      url = "#posts"
      weight = 20
    [[languages.ja.menu.main]]
      name = "業績"
      url = "achievements/"
      weight = 30
    [[languages.ja.menu.main]]
      name = "受賞"
      url = "awards/"
      weight = 35
    [[languages.ja.menu.main]]
      name = "プロジェクト"
      url = "projects-list/"
      weight = 40
    [[languages.ja.menu.main]]
      name = "講義"
      url = "teaching/"
      weight = 50
    [[languages.ja.menu.main]]
      name = "アクセス"
      url = "access/"
      weight = 70
    [[languages.ja.menu.main]]
      name = "久住"
      url = "about/"
      weight = 60

[languages.en]
  languageName = "English"
  contentDir = "content/en"
  weight = 2

  [languages.en.menu]
    [[languages.en.menu.main]]
      name = "Home"
      url = "/"
      weight = 10
    [[languages.en.menu.main]]
      name = "Awards"
      url = "awards/"
      weight = 20
    [[languages.en.menu.main]]
      name = "Achievements"
      url = "achievements/"
      weight = 30      

[params]
  # Site description
  description = "Hisazumi Laboratory"

[security.funcs]
  getenv = ['^HUGO_', '^CI$', 'WC_POST_CSS']

[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "(js|scripts|javascript)"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"
